navsat_transform_node:
  ros__parameters:
    frequency: 10.0
    delay: 0.0
    magnetic_declination_radians: 0.0  # Adjust based on location
    yaw_offset: 0.0  # If IMU is not aligned with robot
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
    gps_frame_id: gps_link
    transform_timeout: 0.0